// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EPrescription$Type } from "./EPrescription";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EPrescription"]: EPrescription$Type;
    ["contracts/EPrescription.sol:EPrescription"]: EPrescription$Type;
  }

  interface ContractTypesMap {
    ["EPrescription"]: GetContractReturnType<EPrescription$Type["abi"]>;
    ["contracts/EPrescription.sol:EPrescription"]: GetContractReturnType<EPrescription$Type["abi"]>;
  }
}
